'use client';

import { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/components/ui/use-toast';
import { Loader2 } from 'lucide-react';

const micrositeSchema = z.object({
  unit_id: z.string().min(1, 'Property is required'),
  slug: z.string().optional(), // Auto-generated, not required from user
  seo_title: z.string().optional(),
  seo_description: z.string().optional(),
  seo_keywords: z.string().optional(),
  is_published: z.boolean().default(false),
  template_id: z.string().optional(),
});

type MicrositeFormData = z.infer<typeof micrositeSchema>;

interface MicrositeFormProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  microsite?: any;
  mode: 'create' | 'edit';
  onSuccess?: () => void;
}

export function MicrositeForm({
  open,
  onOpenChange,
  microsite,
  mode,
  onSuccess,
}: MicrositeFormProps) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
    setValue,
    watch,
  } = useForm<MicrositeFormData>({
    resolver: zodResolver(micrositeSchema),
    defaultValues: {
      is_published: false,
    },
  });

  // Fetch dependencies
  const { data: units } = useQuery<any>({
    queryKey: ['units'],
    queryFn: () => api.get('/properties/units', { limit: 1000 }),
    enabled: open,
  });

  useEffect(() => {
    if (microsite && open && mode === 'edit') {
      setValue('unit_id', microsite.unit_id?.toString() || '');
      // Slug is read-only, don't set it in form
      setValue('seo_title', microsite.seo_title || '');
      setValue('seo_description', microsite.seo_description || '');
      setValue('seo_keywords', microsite.seo_keywords || '');
      setValue('is_published', microsite.is_published || false);
      setValue('template_id', microsite.template_id?.toString() || 'none');
    } else if (open && mode === 'create') {
      reset({
        is_published: false,
      });
    }
  }, [microsite, open, mode, setValue, reset]);

  // Slug is auto-generated by backend - no need to set it in frontend

  const mutation = useMutation({
    mutationFn: (data: MicrositeFormData) => {
      const payload: any = {
        unit_id: parseInt(data.unit_id),
        // Slug is auto-generated by backend in create mode, don't send it
        // In edit mode, slug should not be changed
        seo_title: data.seo_title || null,
        seo_description: data.seo_description || null,
        seo_keywords: data.seo_keywords || null,
        is_published: data.is_published,
        template_id:
          data.template_id && data.template_id !== 'none' ? parseInt(data.template_id) : null,
      };

      if (mode === 'create') {
        // Backend will auto-generate unique slug
        return api.post('/microsites', payload);
      } else {
        // Don't allow slug changes in edit mode
        return api.put(`/microsites/${microsite.id}`, payload);
      }
    },
    onSuccess: () => {
      toast({
        title: 'Success',
        description:
          mode === 'create' ? 'Microsite created successfully' : 'Microsite updated successfully',
      });
      queryClient.invalidateQueries({ queryKey: ['microsites'] });
      reset();
      onOpenChange(false);
      onSuccess?.();
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.response?.data?.error || `Failed to ${mode} microsite`,
        variant: 'destructive',
      });
    },
    onSettled: () => {
      setIsSubmitting(false);
    },
  });

  const onSubmit = (data: MicrositeFormData) => {
    setIsSubmitting(true);
    mutation.mutate(data);
  };

  const unitsList = units?.data || [];

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{mode === 'create' ? 'Create Microsite' : 'Edit Microsite'}</DialogTitle>
          <DialogDescription>
            {mode === 'create'
              ? 'Create a new property microsite for showcasing'
              : 'Update microsite information'}
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div>
            <Label htmlFor="unit_id">Property *</Label>
            <Select
              value={watch('unit_id') || ''}
              onValueChange={(value) => setValue('unit_id', value)}
              disabled={mode === 'edit'}
            >
              <SelectTrigger className={errors.unit_id ? 'border-red-500' : ''}>
                <SelectValue placeholder="Select property" />
              </SelectTrigger>
              <SelectContent>
                {unitsList.map((unit: any) => (
                  <SelectItem key={unit.id} value={unit.id.toString()}>
                    {unit.name} - {unit.building?.name || 'N/A'}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {errors.unit_id && (
              <p className="text-sm text-red-500 mt-1">{errors.unit_id.message}</p>
            )}
          </div>


          <div>
            <Label htmlFor="seo_title">SEO Title</Label>
            <Input
              id="seo_title"
              {...register('seo_title')}
              placeholder="Property Title for Search Engines"
            />
          </div>

          <div>
            <Label htmlFor="seo_description">SEO Description</Label>
            <Textarea
              id="seo_description"
              {...register('seo_description')}
              rows={3}
              placeholder="Meta description for search engines"
            />
          </div>

          <div>
            <Label htmlFor="seo_keywords">SEO Keywords</Label>
            <Input
              id="seo_keywords"
              {...register('seo_keywords')}
              placeholder="keyword1, keyword2, keyword3"
            />
            <p className="text-xs text-muted-foreground mt-1">
              Comma-separated keywords for SEO
            </p>
          </div>

          <div className="flex items-center space-x-2">
            <input
              type="checkbox"
              id="is_published"
              checked={watch('is_published')}
              onChange={(e) => setValue('is_published', e.target.checked)}
              className="h-4 w-4 rounded border-gray-300"
            />
            <Label htmlFor="is_published">Published</Label>
            <p className="text-xs text-muted-foreground ml-2">
              Published microsites are publicly accessible
            </p>
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={isSubmitting}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={isSubmitting}>
              {isSubmitting && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
              {mode === 'create' ? 'Create Microsite' : 'Update Microsite'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

